#!/sbin/sh

. "$env";

cd "${tmp}/rz_system" && [ "$(ls)" ] || exit 0;

chmod -R 0755 .;

## libsecure_storage patch ##
print "Setting libsecure_storage permissions...";

# Change permissions
chmod 0644 ./vendor/lib/libsecure_storage.so;
chmod 0644 ./vendor/lib64/libsecure_storage.so;

## Vendor fimc binaries patch ##
print "Setting fimc binaries permissions...";
chmod 0644 ./vendor/firmware/fimc_is_lib.bin;
chmod 0644 ./vendor/firmware/fimc_is_rta_2l2_3h1.bin;

print "Copying patched files into data";
cp -rf ${tmp}/rz_system /data/rz_system;
chmod 0755 /data/rz_system;

#### Originally written by @djb77 ####
# Remove unwanted file from /system/app/mcRegistry
rm -f /system/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin;

# Remove RMM State Lock
rm -rf /system/priv-app/Rlc;
sed -i -- 's/ro.security.vaultkeeper.feature=1/ro.security.vaultkeeper.feature=0/g' $build_prop;

# Remove Security Log Agent
rm -rf /system/app/SecurityLogAgent;

# Delete Wakelock.sh (in case these were installed somewhere else)
rm -f /magisk/phh/su.d/wakelock*;
rm -f /su/su.d/wakelock*;
rm -f /system/su.d/wakelock*;
rm -f /system/etc/init.d/wakelock*;

exit 0;
